var products = [
    {
        image: "nike-phantom.jpg",
        title: "Nike Phantom Cleats",
        price: "270",
        sizes: ["7.5", "8", "8.5", "9", "9.5", "10"],
        description: "This shoe features an extra lace and comes in various colors",
        colors: ["white", "grey", "red"],
        brand: "Nike",
        categories: ["cleats", "men", "women", "youth"],
        product_id: "a1001"
    },
    {
        image: "Adidas-Predators.jpg",
        title: "Adidas Predators Cleats",
        price: "110",
        sizes: ["7.5", "8", "8.5", "9", "9.5", "10"],
        description: "This shoe features 3 different types of colors ",
        colors: ["blue", "green", "black"],
        brand: "Adidas",
        categories: ["cleats", "men", "women", "youth"],
        product_id: "a2001"
    },
    {
        image: "adidas-x-16.jpg",
        title: "Adidas X 16 Cleats",
        price: "190",
        sizes: ["7.5", "8", "8.5", "9", "9.5", "10"],
        description: "This shoe features 2 differnt types of colors",
        colors: ["white", "black"],
        brand: "Adidas",
        categories: ["cleats", "men", "women", "youth"],
        product_id: "a3001"
    },
    {
        image: "Mercurial-Superfly.jpg",
        title: "Mercurial Superfly Cleats",
        price: "200",
        sizes: ["7.5", "8", "8.5", "9", "9.5", "10"],
        description: "This shoe features an extra lace and comes in various colors",
        colors: ["white", "grey"],
        brand: "Nike",
        categories: ["cleats", "men", "women", "youth"],
        product_id: "a4001"
    },
    {
        image: "Nemeziz.jpg",
        title: "Nemeziz Cleats",
        price: "120",
        sizes: ["7.5", "8", "8.5", "9", "9.5", "10"],
        description: "This shoe features an extra lace and comes in various colors",
        colors: ["white", "green", "orange"],
        brand: "Adidas",
        categories: ["cleats", "men", "women", "youth"],
        product_id: "a6001"
    },
    {
        image: "Nike-Superfly-VI.jpg",
        title: "Nike Superfly VI Cleats",
        price: "150",
        sizes: ["7.5", "8", "8.5", "9", "9.5", "10"],
        description: "This shoe features an extra lace and comes in various colors",
        colors: ["Blue", "White"],
        brand: "Nike",
        categories: ["cleats", "men", "women", "youth"],
        product_id: "a7001"
    },
    {
        image: "Nike-Hypervenom-Phantom 2.jpg",
        title: "Nike Hypervenom Phantom Cleats",
        price: "290",
        sizes: ["7.5", "8", "8.5", "9", "9.5", "10"],
        description: "This shoe features an extra lace and comes in various colors",
        colors: ["white", "grey", "red"],
        brand: "Nike",
        categories: ["cleats", "men", "women", "youth"],
        product_id: "a8001"
    },
    {
        image: "World-Cup-2018-ball.jpg",
        title: "2018 Fifa Worl Cup Ball",
        price: "100",
        sizes: ["3", "4", "5"],
        description: "The ball comes in three different colors",
        colors: ["white", "grey", "blue"],
        brand: "Fifa",
        categories: ["soccer ball"],
        product_id: "b5001"
    },
    {
        image: "CR7-soccer-ball.jpg",
        title: "CR7 Soccer Ball",
        price: "90",
        sizes: ["3", "4", "5"],
        description: "This soccer ball comes in three different sizes",
        colors: ["white", "grey", "red"],
        brand: "CR7",
        categories: ["soccer ball"],
        product_id: "b1001"
    },
    {
        image: "Training-cones.jpg",
        title: "Training Cones",
        price: "20",
        sizes: ["s"],
        description: "The cones come in a pack of 20",
        colors: ["Orange"],
        brand: "Nike",
        categories: ["cones"],
        product_id: "b2001"
    },
    {
        image: "Adidas-soccer-gloves.jpg",
        title: "Keeper Gloves",
        price: "100",
        sizes: ["S", "M", "L"],
        description: "This shoe features 3 different colors",
        colors: ["white", "grey", "red"],
        brand: "Nike",
        categories: ["soccer gloves", "men", "women", "youth"],
        product_id: "a9001"
    },
    {
        image: "training-soccer-goals.jpg",
        title: "Training Small Goals",
        price: "70",
        sizes: ["S"],
        description: "The training small goals come in a pack of 2",
        colors: ["white"],
        brand: "Nike",
        categories: ["small goals"],
        product_id: "b4001"
    },
    {
        image: "Training-shirts.jpg",
        title: "Training Shirts",
        price: "15",
        sizes: ["S", "M", "L", "XL"],
        description: "These shirts come in a pack of three",
        colors: ["white", "grey", "black"],
        brand: "Adidas",
        categories: ["shirts", "men", "women", "youth"],
        product_id: "b3001"
    },
    {
        image: "RM-practice-kit.jpg",
        title: "Real Madrid Training kit",
        price: "190",
        sizes: ["S", "M", "L", "XL"],
        description: "The Real Madrid Training Kit comes with a Wind braker with the logo and some sweat pants",
        colors: ["white", "Blue", "Black"],
        brand: "Real Madrid",
        categories: ["Training kit", "men", "women", "youth"],
        product_id: "b6001"
    },
    {
        image: "Player-kit.jpg",
        title: " Real Madrid player kit",
        price: "200",
        sizes: ["S", "M", "L", "XL"],
        description: "The Real Madrid player kit features a jersey with your own name and some shorts and long socks",
        colors: ["white", "Black", "Blue"],
        brand: "Real Madrid",
        categories: ["jerseys", "men", "women", "youth"],
        product_id: "b7001"
    },
    {
        image: "Real-Madrid3.jpg",
        title: "Real Madrid Blue jersey",
        price: "110",
        sizes: ["S", "M", "L", "XL"],
        description: "This Jersey features any number and name you want",
        colors: ["Blue"],
        brand: "Real Madrid",
        categories: ["jerseys", "men", "women", "youth"],
        product_id: "b8001"
    },
    {
        image: "Real-Madrid.jpg",
        title: "Real Madrid White Jersey",
        price: "110",
        sizes: ["S", "M", "L", "XL"],
        description: "This Jersey features any number and name you want",
        colors: ["white"],
        brand: "Real Madrid",
        categories: ["jerseys", "men", "women", "youth"],
        product_id: "b9001"
    },
    {
        image: "Real-Madrid2.jpg",
        title: "Real Madrid Red jersey",
        price: "110",
        sizes: ["S", "M", "L", "XL"],
        description: "This Jersey features any number and name you want",
        colors: ["red"],
        brand: "Real Madrid",
        categories: ["jerseys", "men", "women", "youth"],
        product_id: "c1001"
    },
    {
        image: "Barcelona.jpg",
        title: "Barcelona 2018-19 Home JERSEY",
        price: "150",
        sizes: ["S", "M", "L", "XL"],
        description: "This Jersey features any number and name you want",
        colors: ["red/blue"],
        brand: "Barcelona",
        categories: ["jerseys", "men", "women", "youth"],
        product_id: "C2001"
    },
    {
        image: "Barcelona-2k18.jpg",
        title: "Barcelona 2017-18 Home Jersey",
        price: "160",
        sizes: ["S", "M", "L", "9", "9.5", "10"],
        description: "This Jersey features any number and name you want",
        colors: ["red/blue"],
        brand: "Barcelona",
        categories: ["jerseys", "men", "women", "youth"],
        product_id: "C3001"
    },
    {
        image: "pink-barcelona.jpg",
        title: "Barcelona 2018-19 Away Jersey",
        price: "160",
        sizes: ["S", "M", "L", "9", "9.5", "10"],
        description: "This is the newest Barcelona jersey",
        colors: ["lightcoral"],
        brand: "Barcelona",
        categories: ["jerseys", "men", "women", "youth"],
        product_id: "C4001"
    },
];